global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      # set target 'localhost:9090' to run app in docker
      - targets: ['host.docker.internal:8081']
